# This is a basic workflow to help you get started with Actions
#---------------------------------------------------
# GitHub Action Test Part-1
#
# Copyleft (c) by me 2022
#---------------------------------------------------
name: My-GitHub-Action-Basics
env:
  APPLICATION_NAME: "MyTest"
  Deploy_PACKAGE_NAME: "test-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master  

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from testing job"
    
    - name: Execute for commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is Job variable1"
      VAR2: "This is Job variable2"
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from deploy job"
      
    - name: Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "VAR2 = ${{ env.VAR2 }}"
        echo "VAR3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Local variable"
      
    - name: Printing Deployment packege
      run: echo "Deploy package name is ${{ env.Deploy_PACKAGE_NAME }}"

    - name: Lets test some packages if they are here 1
      run: aws --version
      
    - name: Lets test some packages if they are here 2
      run: zip --version
