# This is a basic workflow to help you get started with Actions
#---------------------------------------------------
# GitHub Action Test Part-1
#
# Copyleft (c) by me 2022
#---------------------------------------------------
name: My-GitHub-Action-Basics
env:
  APPLICATION_NAME: "MyTest"
  Deploy_PACKAGE_NAME: "test-deploy-ver-{{ github.sha }}"

on:
  push:
    branches:
      - master  

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from testing job"
    
    - name: Execute for commands
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run: ls -la
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from deploy job"
      
    - name: Printing Deployment packege
      run: echo "Deploy package name is ${{ env.Deploy_PACKAGE_NAME }}"
